### PR TITLE
Changed index.html

### PR DESCRIPTION
**Pull request by ryan-schlientz**
A Comment

### CODE REVIEW

**Comment by cmsong** [comment]
This is bad mmkay

**Review by danmarcolongo — APPROVED** [review]
I approve

**Comment by flubbid** [comment]
I think things are ok

**Comment by blappa** [comment]
Good Job

**Comment by Kobs21** [comment]
Leave a comment

**Review by Kobs21 — CHANGES_REQUESTED** [review]
No me gusta

**Comment by Nicoleta13** [comment]
Proud of you

**Review by Kobs21 — COMMENTED** [review]
approve

**Pull request merged**
